name: Simple Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make test
      run: make test

  build-32bit:
    runs-on: ubuntu-latest
    container: i386/ubuntu:22.04

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: apt-get update && apt-get install -y clang gcc make python3
    - name: make test
      run: make test
